[tool.flake8]
max-line-length = 88
exclude = [
    '.git',
    '__pycache__',
    'docs/source/conf.py',
    'old',
    'build',
    'dist',
    'venv'
]
max-complexity = 19
extend-ignore = ['E203', 'W503', 'E241']

[tool.mypy]
python_version = "3.10"
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
exclude = [

    '.git',
    '__pycache__',
    'docs/source/conf.py',
    'old',
    'build',
    'dist',
    'venv'
]
plugins = [
    "numpy.typing.mypy_plugin"
]

[tool.black]
line-length = 88
preview = true
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
